namespace UberStrike.Realtime.Client
{
	public enum IGameRoomEventsType
	{
		PowerUpPicked = 12,
		SetPowerupState = 13,
		ResetAllPowerups = 14,
		DoorOpen = 15,
		DisconnectCountdown = 16,
		MatchStartCountdown = 17,
		MatchStart = 18,
		MatchEnd = 19,
		TeamWins = 20,
		WaitingForPlayers = 21,
		PrepareNextRound = 22,
		AllPlayers = 23,
		AllPlayerDeltas = 24,
		AllPlayerPositions = 25,
		PlayerDelta = 26,
		PlayerJumped = 27,
		PlayerRespawnCountdown = 28,
		PlayerRespawned = 29,
		PlayerJoinedGame = 30,
		JoinGameFailed = 31,
		PlayerLeftGame = 32,
		PlayerChangedTeam = 33,
		JoinedAsSpectator = 34,
		PlayersReadyUpdated = 35,
		DamageEvent = 36,
		PlayerKilled = 37,
		UpdateRoundScore = 38,
		KillsRemaining = 39,
		LevelUp = 40,
		KickPlayer = 41,
		QuickItemEvent = 42,
		SingleBulletFire = 43,
		PlayerHit = 44,
		RemoveProjectile = 45,
		EmitProjectile = 46,
		EmitQuickItem = 47,
		ActivateQuickItem = 48,
		ChatMessage = 49
	}
}
