name: Unity Windows Build EXE

on:
  pull_request

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build Windows Player
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          buildName: UberStrike
          buildsPath: Build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WindowsBuild
          path: Build/StandaloneWindows64
