name: Unity Windows Build EXE

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Detect Unity version
        id: unityVersion
        run: |
          $version = (Select-String -Path "ProjectSettings/ProjectVersion.txt" -Pattern "m_EditorVersion").Line.Split()[1]
          echo "VERSION=$version" >> $env:GITHUB_ENV

      - name: Build Windows 64-bit Player
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          unityVersion: ${{ env.VERSION }}
          buildName: UberStrike.exe
          buildsPath: Build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WindowsBuild
          path: Build/StandaloneWindows64