name: Unity Windows Build EXE

on:
  pull_request:
    types: [ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/unity3d
            ~/.local/share/unity3d
          key: Library-${{ runner.os }}-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Build Windows Player
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          buildName: UberStrike
          buildPath: Build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WindowsBuild
          path: Build/StandaloneWindows64
